name: Security Scan

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  owasp-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Security Check
        run: echo "Security Scan Started Successfully!"
